### ISSUE TITLE
Improve support for unknown paths

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#136]
Improve the support in case of some path on EV3Dev is not present in latest version of ev3dev.

**Comment by jabrena** [comment]
Fixed:

``` bash
Caused by: java.lang.RuntimeException: The path doesn't exist: /sys/class/lego-sensors
	at ev3dev.utils.Sysfs.getElements(Sysfs.java:88)
	at ev3dev.hardware.EV3DevSensorDevice.detect(EV3DevSensorDevice.java:71)
	at ev3dev.hardware.EV3DevSensorDevice.<init>(EV3DevSensorDevice.java:39)
	at ev3dev.hardware.sensors.BaseSensor.<init>(BaseSensor.java:15)
	at ev3dev.hardware.sensors.ev3.EV3IRSensor.<init>(EV3IRSensor.java:63)
	at examples.sensors.ev3.IRSensorDemo.<clinit>(IRSensorDemo.java:11)
```

**Comment by jabrena** [comment]
Fixed
