### ISSUE TITLE
Refactor RpLidarLowLevelDriver

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#206]
Sometimes, RpLidarLowLevelDriver raise an Exception on the thread. At the moment, the exception is handled but it is necessary to improve the code.

``` 
2017-03-26 19:47:21 [Thread-1] ERROR e.s.s.service.RpLidarLowLevelDriver - null
java.lang.NullPointerException
	at ev3dev.sensors.slamtec.RPLidarA1Driver.lambda$containAngle$0(RPLidarA1Driver.java:71)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at ev3dev.sensors.slamtec.RPLidarA1Driver.containAngle(RPLidarA1Driver.java:71)
	at ev3dev.sensors.slamtec.RPLidarA1Driver.handleMeasurement(RPLidarA1Driver.java:64)
	at ev3dev.sensors.slamtec.service.RpLidarLowLevelDriver.parseScan(RpLidarLowLevelDriver.java:339)
	at ev3dev.sensors.slamtec.service.RpLidarLowLevelDriver.parseData(RpLidarLowLevelDriver.java:217)
	at ev3dev.sensors.slamtec.service.RpLidarLowLevelDriver$ReadSerialThread.run(RpLidarLowLevelDriver.java:369)
	at java.lang.Thread.run(Thread.java:745)
2017-03-26 19:47:22 [main] INFO  examples.Demo - Iteration: 57, Measures: 299
```

**Comment by jabrena** [comment]
https://github.com/camearle20/LIDARIO/blob/master/LIDARIO.java

**Comment by jabrena** [comment]
https://github.com/ocherny/LIDARSweep/blob/master/java/Lidar2/src/main/java/ath/lidar/LidarFrame.java

**Comment by jabrena** [comment]
https://github.com/AMAP-dev/LidarShotTxtFormat/tree/master/src/main/java/fr/amap/lidar/format/shot

**Comment by jabrena** [comment]
https://github.com/pjrader1/sota-lidar-viewer/tree/master/src/main/java

**Comment by jabrena** [comment]
https://github.com/d33z/OpenLMS111/blob/master/tools/LMSVisualizationPanel.java

**Comment by jabrena** [comment]
https://github.com/d33z/OpenLMS111/blob/master/src/Position.java

**Comment by jabrena** [comment]
https://github.com/ksmiller99/HelloIOIOScribbler/tree/master/src/main/java/millerk31/rplidar

**Comment by jabrena** [comment]
Rejected by LEAN
