### ISSUE TITLE
[CORE] Certification // EV3 Brick + ev3dev-jessie-2017-02-11 + Java 8 + ev3dev-lang-java v0.6.0-SNAPSHOT

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#259]
```gherkin
Feature: Develop the library EV3Dev-lang-java
In the third generation of Lego Mindstorms, 
it is possible to install a complete Linux distribution and a complete Oracle JRE. 
It is necessary to develop a library to use the hardware compatible with EV3Dev.

    Scenario: Certificate develop branch
        Given The library EV3Dev-lang-java
        And The code was changed in several points
        Then It is necessary to execute a complete regression to ensure 0 problems
```

Related issue:
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/178

**Comment by jabrena** [comment]
``` 
2017-06-03 10:17:19 [main] TRACE ev3dev.hardware.EV3DevPlatforms - /sys/class/power_supply/legoev3-battery
2017-06-03 10:17:19 [main] ERROR ev3dev.hardware.EV3DevPlatforms - Platform not supported: Mac OS X 10.12.4
Exception in thread "main" java.lang.RuntimeException: Platform not supported: Mac OS X 10.12.4
	at ev3dev.hardware.EV3DevPlatforms.getPlatform(EV3DevPlatforms.java:44)
	at examples.ev3dev.hardware.PlatformTest.main(PlatformTest.java:12)
```

**Comment by jabrena** [comment]
**Actuators Tests:**

SoundDemo: Passed
LCDDrawIconsTest: Passed
LCDDrawImagesTest: Passed
LCDDrawLinesTest: Passed
LCDDrawRectanglesTest: Passed
LCDFontTest: Passed
LCDTest: Passed
LCDWriteTextTest: Passed

**Comment by jabrena** [comment]
- TTSDemo: Passed
- TTSDemo2: Passed

**Comment by jabrena** [comment]
**Actuators Tests:**

- BatteryDemo: Partially (Review Units: getBatteryCurrent)
- ButtonTest: Failed (Slow performace)
- ButtonTest2: Failed (Remove this support in this iteration)
- ColorSensorDemo: Passed
- ColorSensorDemo2: Passed
- ColorSensorDemo3: Passed
- ColorSensorMultipleDemo: Passed
- GyroSensorDemo: Passed
- GyroSensorDemo2: Passed
- GyroSensorDemo3: Passed
- IRSensorDemo: Passed
- IRSensorDemo2: Passed
- IRSensorDemo3: Passed
- TouchSensorDemo: Passed
- USSensorDemo: Passed
- USSensorDemo2: Passed

**Comment by jabrena** [comment]
**Summary:**
It is necessary to remove the support for Buttons in this iteration and open the issue again

**Comment by jabrena** [comment]
Create release of the project. The library is stable. It is necessary to certificate for BrickPi+ & PiStorms
