### ISSUE TITLE
[ROS2] Install ROS2_java on Ubuntu

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#262]
```gherkin
Feature: Test ROS2 with Java
It is necessary to analyze the difficult to use the Java library for ROS2

    Background: The host used to test the library has Ubuntu.

    Scenario: Test in local the library
        Given The library ros2_java
        Then It is necessary to test the classic example Listener & Talker
        And evaluate how to complex is the usage of the library for a Robotics environment.
```

Related issue:
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/254

**Comment by jabrena** [comment]
Software to install:

```
apt-get install -y --no-install-recommends openjdk-8-jdk 
apt-get install -y --no-install-recommends libasio-dev 
apt-get install -y --no-install-recommends libtinyxml2-dev
```

**Comment by jabrena** [comment]
Hi @esteve, 

What is the other dependencies that a ubuntu system requires to execute this step?

```
jabrena@jabrena-VirtualBox:~/ros2_java/ament_ws$ src/ament/ament_tools/scripts/ament.py build --parallel --symlink-install --isolated
Traceback (most recent call last):
  File "src/ament/ament_tools/scripts/ament.py", line 156, in <module>
    sys.exit(main() or 0)
  File "/home/jabrena/ros2_java/ament_ws/src/ament/ament_tools/ament_tools/commands/ament.py", line 50, in main
    sysargs,
  File "/home/jabrena/ros2_java/ament_ws/src/ament/osrf_pycommon/osrf_pycommon/cli_utils/verb_pattern.py", line 105, in create_subparsers
    sysargs,
  File "/home/jabrena/ros2_java/ament_ws/src/ament/osrf_pycommon/osrf_pycommon/cli_utils/verb_pattern.py", line 58, in call_prepare_arguments
    return func(*func_args) or parser
  File "/home/jabrena/ros2_java/ament_ws/src/ament/ament_tools/ament_tools/verbs/build/cli.py", line 132, in prepare_arguments
    build_type_impl = build_type.load()()
  File "src/ament/ament_tools/scripts/ament.py", line 108, in load
    'ament_tools.build_types.%s' % self.build_type)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/jabrena/ros2_java/ament_ws/src/ament/ament_tools/ament_tools/build_types/ament_python.py", line 21, in <module>
    import setuptools
ImportError: No module named 'setuptools'
```

**Comment by jabrena** [comment]
```
build-essential cppcheck cmake libopencv-dev python-empy python3-dev python3-empy python3-nose python3-pip python3-setuptools python3-vcstool
```

**Comment by jabrena** [comment]
``` 
java -Djava.library.path=/home/jabrena/ros2_java/ros2_java_ws/install_isolated/visualization_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/trajectory_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/tinyxml_vendor/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/stereo_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/std_srvs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/shape_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/sensor_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcljava/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcl_lifecycle/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcl/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/nav_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/diagnostic_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/geometry_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/actionlib_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/std_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcl_interfaces/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/lifecycle_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/example_interfaces/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/builtin_interfaces/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rosidl_typesupport_cpp/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rosidl_typesupport_c/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rmw_fastrtps_cpp/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rosidl_typesupport_introspection_cpp/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rosidl_typesupport_introspection_c/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rmw/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rosidl_generator_c/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcljava_common/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcutils/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/poco_vendor/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/fastrtps/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/fastcdr/lib -cp /home/jabrena/ros2_java/ros2_java_ws/install_isolated/visualization_msgs/share/visualization_msgs/java/visualization_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/trajectory_msgs/share/trajectory_msgs/java/trajectory_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/stereo_msgs/share/stereo_msgs/java/stereo_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/std_srvs/share/std_srvs/java/std_srvs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/shape_msgs/share/shape_msgs/java/shape_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/sensor_msgs/share/sensor_msgs/java/sensor_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcljava/share/rcljava/java/rcljava.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/nav_msgs/share/nav_msgs/java/nav_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/diagnostic_msgs/share/diagnostic_msgs/java/diagnostic_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/geometry_msgs/share/geometry_msgs/java/geometry_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/actionlib_msgs/share/actionlib_msgs/java/actionlib_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/std_msgs/share/std_msgs/java/std_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcl_interfaces/share/rcl_interfaces/java/rcl_interfaces_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/lifecycle_msgs/share/lifecycle_msgs/java/lifecycle_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/example_interfaces/share/example_interfaces/java/example_interfaces_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/builtin_interfaces/share/builtin_interfaces/java/builtin_interfaces_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcljava_common/share/rcljava_common/java/rcljava_common.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcljava_common/share/rcljava_common/java/slf4j-jdk14-1.7.21.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcljava_common/share/rcljava_common/java/slf4j-log4j12-1.7.21.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcljava_common/share/rcljava_common/java/log4j-1.2.17.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcljava_common/share/rcljava_common/java/slf4j-api-1.7.21.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcljava_examples/share/rcljava_examples/java/rcljava_examples.jar:. org.ros2.rcljava.examples.Listener
```

**Comment by jabrena** [comment]
```  
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/jabrena/ros2_java/ros2_java_ws/build_isolated/rcljava_common/jars/slf4j-jdk14-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/jabrena/ros2_java/ros2_java_ws/build_isolated/rcljava_common/jars/slf4j-log4j12-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
May 07, 2017 4:35:09 PM org.ros2.rcljava.common.JNIUtils loadLibrary
INFO: Loading library: org_ros2_rcljava_rcl_java
May 07, 2017 4:35:09 PM org.ros2.rcljava.RCLJava rclJavaInit
INFO: Using RMW implementation: rmw_fastrtps_cpp
May 07, 2017 4:35:09 PM org.ros2.rcljava.common.JNIUtils loadLibrary
INFO: Loading library: org_ros2_rcljava_node__node_impl
May 07, 2017 4:35:09 PM org.ros2.rcljava.common.JNIUtils loadLibrary
INFO: Loading library: std_msgs_msg__string__rosidl_typesupport_introspection_c
May 07, 2017 4:35:09 PM org.ros2.rcljava.common.JNIUtils loadLibrary
INFO: Loading library: org_ros2_rcljava_subscription__subscription_impl
```

**Comment by jabrena** [comment]
java org.ros2.rcljava.examples.Talker

ros2_java also supports services:

On one terminal:

. ~/ros2_java_ws/install_isolated/local_setup.sh
java org.ros2.rcljava.examples.AddTwoIntsService

and on another one:

. ~/ros2_java_ws/install_isolated/local_setup.sh
java org.ros2.rcljava.examples.AddTwoIntsClient

**Comment by jabrena** [comment]
```
java -Djava.library.path=/home/jabrena/ros2_java/ros2_java_ws/install_isolated/visualization_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/trajectory_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/tinyxml_vendor/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/stereo_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/std_srvs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/shape_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/sensor_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcljava/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcl_lifecycle/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcl/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/nav_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/diagnostic_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/geometry_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/actionlib_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/std_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcl_interfaces/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/lifecycle_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/example_interfaces/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/builtin_interfaces/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rosidl_typesupport_cpp/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rosidl_typesupport_c/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rmw_fastrtps_cpp/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rosidl_typesupport_introspection_cpp/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rosidl_typesupport_introspection_c/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rmw/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rosidl_generator_c/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcljava_common/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcutils/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/poco_vendor/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/fastrtps/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/fastcdr/lib -cp /home/jabrena/ros2_java/ros2_java_ws/install_isolated/visualization_msgs/share/visualization_msgs/java/visualization_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/trajectory_msgs/share/trajectory_msgs/java/trajectory_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/stereo_msgs/share/stereo_msgs/java/stereo_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/std_srvs/share/std_srvs/java/std_srvs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/shape_msgs/share/shape_msgs/java/shape_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/sensor_msgs/share/sensor_msgs/java/sensor_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcljava/share/rcljava/java/rcljava.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/nav_msgs/share/nav_msgs/java/nav_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/diagnostic_msgs/share/diagnostic_msgs/java/diagnostic_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/geometry_msgs/share/geometry_msgs/java/geometry_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/actionlib_msgs/share/actionlib_msgs/java/actionlib_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/std_msgs/share/std_msgs/java/std_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcl_interfaces/share/rcl_interfaces/java/rcl_interfaces_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/lifecycle_msgs/share/lifecycle_msgs/java/lifecycle_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/example_interfaces/share/example_interfaces/java/example_interfaces_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/builtin_interfaces/share/builtin_interfaces/java/builtin_interfaces_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcljava_common/share/rcljava_common/java/rcljava_common.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcljava_common/share/rcljava_common/java/slf4j-jdk14-1.7.21.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcljava_common/share/rcljava_common/java/slf4j-log4j12-1.7.21.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcljava_common/share/rcljava_common/java/log4j-1.2.17.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcljava_common/share/rcljava_common/java/slf4j-api-1.7.21.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcljava_examples/share/rcljava_examples/java/rcljava_examples.jar:. org.ros2.rcljava.examples.Talker
``` 

```
java -Djava.library.path=/home/jabrena/ros2_java/ros2_java_ws/install_isolated/visualization_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/trajectory_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/tinyxml_vendor/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/stereo_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/std_srvs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/shape_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/sensor_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcljava/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcl_lifecycle/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcl/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/nav_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/diagnostic_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/geometry_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/actionlib_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/std_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcl_interfaces/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/lifecycle_msgs/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/example_interfaces/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/builtin_interfaces/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rosidl_typesupport_cpp/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rosidl_typesupport_c/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rmw_fastrtps_cpp/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rosidl_typesupport_introspection_cpp/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rosidl_typesupport_introspection_c/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rmw/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rosidl_generator_c/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcljava_common/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcutils/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/poco_vendor/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/fastrtps/lib:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/fastcdr/lib -cp /home/jabrena/ros2_java/ros2_java_ws/install_isolated/visualization_msgs/share/visualization_msgs/java/visualization_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/trajectory_msgs/share/trajectory_msgs/java/trajectory_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/stereo_msgs/share/stereo_msgs/java/stereo_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/std_srvs/share/std_srvs/java/std_srvs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/shape_msgs/share/shape_msgs/java/shape_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/sensor_msgs/share/sensor_msgs/java/sensor_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcljava/share/rcljava/java/rcljava.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/nav_msgs/share/nav_msgs/java/nav_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/diagnostic_msgs/share/diagnostic_msgs/java/diagnostic_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/geometry_msgs/share/geometry_msgs/java/geometry_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/actionlib_msgs/share/actionlib_msgs/java/actionlib_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/std_msgs/share/std_msgs/java/std_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcl_interfaces/share/rcl_interfaces/java/rcl_interfaces_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/lifecycle_msgs/share/lifecycle_msgs/java/lifecycle_msgs_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/example_interfaces/share/example_interfaces/java/example_interfaces_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/builtin_interfaces/share/builtin_interfaces/java/builtin_interfaces_messages.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcljava_common/share/rcljava_common/java/rcljava_common.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcljava_common/share/rcljava_common/java/slf4j-jdk14-1.7.21.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcljava_common/share/rcljava_common/java/slf4j-log4j12-1.7.21.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcljava_common/share/rcljava_common/java/log4j-1.2.17.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcljava_common/share/rcljava_common/java/slf4j-api-1.7.21.jar:/home/jabrena/ros2_java/ros2_java_ws/install_isolated/rcljava_examples/share/rcljava_examples/java/rcljava_examples.jar:. org.ros2.rcljava.examples.Talker
```

**Comment by jabrena** [comment]
```  
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/jabrena/ros2_java/ros2_java_ws/build_isolated/rcljava_common/jars/slf4j-jdk14-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/jabrena/ros2_java/ros2_java_ws/build_isolated/rcljava_common/jars/slf4j-log4j12-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
May 07, 2017 4:45:00 PM org.ros2.rcljava.common.JNIUtils loadLibrary
INFO: Loading library: org_ros2_rcljava_rcl_java
May 07, 2017 4:45:01 PM org.ros2.rcljava.RCLJava rclJavaInit
INFO: Using RMW implementation: rmw_fastrtps_cpp
May 07, 2017 4:45:01 PM org.ros2.rcljava.common.JNIUtils loadLibrary
INFO: Loading library: org_ros2_rcljava_node__node_impl
May 07, 2017 4:45:01 PM org.ros2.rcljava.common.JNIUtils loadLibrary
INFO: Loading library: example_interfaces_srv__add_two_ints__rosidl_typesupport_introspection_c
May 07, 2017 4:45:01 PM org.ros2.rcljava.common.JNIUtils loadLibrary
INFO: Loading library: org_ros2_rcljava_client__client_impl
May 07, 2017 4:45:01 PM org.ros2.rcljava.common.JNIUtils loadLibrary
INFO: Loading library: example_interfaces_srv__add_two_ints__request__rosidl_typesupport_introspection_c
May 07, 2017 4:45:01 PM org.ros2.rcljava.common.JNIUtils loadLibrary
INFO: Loading library: example_interfaces_srv__add_two_ints__response__rosidl_typesupport_introspection_c
Result of add_two_ints: 5
```

**Comment by jabrena** [comment]
``` 
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/jabrena/ros2_java/ros2_java_ws/build_isolated/rcljava_common/jars/slf4j-jdk14-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/jabrena/ros2_java/ros2_java_ws/build_isolated/rcljava_common/jars/slf4j-log4j12-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
May 07, 2017 4:44:36 PM org.ros2.rcljava.common.JNIUtils loadLibrary
INFO: Loading library: org_ros2_rcljava_rcl_java
May 07, 2017 4:44:36 PM org.ros2.rcljava.RCLJava rclJavaInit
INFO: Using RMW implementation: rmw_fastrtps_cpp
May 07, 2017 4:44:36 PM org.ros2.rcljava.common.JNIUtils loadLibrary
INFO: Loading library: org_ros2_rcljava_node__node_impl
May 07, 2017 4:44:36 PM org.ros2.rcljava.common.JNIUtils loadLibrary
INFO: Loading library: example_interfaces_srv__add_two_ints__rosidl_typesupport_introspection_c
Warning: Setting QoS durability to 'transient local' for service servers can cause them to receive requests from clients that have since terminated.
May 07, 2017 4:44:36 PM org.ros2.rcljava.common.JNIUtils loadLibrary
INFO: Loading library: org_ros2_rcljava_service__service_impl
May 07, 2017 4:44:37 PM org.ros2.rcljava.common.JNIUtils loadLibrary
INFO: Loading library: example_interfaces_srv__add_two_ints__request__rosidl_typesupport_introspection_c
May 07, 2017 4:44:37 PM org.ros2.rcljava.common.JNIUtils loadLibrary
INFO: Loading library: example_interfaces_srv__add_two_ints__response__rosidl_typesupport_introspection_c
Incoming request
a: 2 b: 3
```

**Comment by jabrena** [comment]
In Linux, the variable is empty:

```
jabrena@jabrena-VirtualBox:~/ros2_java/ros2_java_ws$ . ~/ros2_java/ros2_java_ws/install_isolated/local_setup.sh
jabrena@jabrena-VirtualBox:~/ros2_java/ros2_java_ws$ echo $DYLD_LIBRARY_PATH

jabrena@jabrena-VirtualBox:~/ros2_java/ros2_java_ws$ 
```

In order to run the examples, I had to use the value from OSX and changes the path from `/Users` to `/home`

**Comment by jabrena** [comment]
Finally, I could run ROS 2 with Java in the first environment, Ubuntu.
