### ISSUE TITLE
[NAV] Add Support for package: lejos.robotics.objectdetection

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#279]
**Example:**
https://github.com/jonathansmit7/legoNXT/blob/master/src/lego/besturing/FeatureListenerImpl.java
https://github.com/ameysutavani/mindstormprojects/blob/master/EV3%20leJOS/FeatureAvoider/src/FeatureAvoider.java
https://github.com/SoerenJesseGruen/KiPraktikum2016_MS2/blob/master/mclhouses_v2/HouseNavigationModel.java
https://github.com/yunyh/NXT/blob/master/NxtTest/src/NxtMain.java
https://github.com/olivierdedieu/robots/blob/master/CarpetRover/src/Obstacle.java

**Comment by jabrena** [comment]
``` 
package ev3dev.examples.feature;

import ev3dev.examples.pilot.PilotConfig;
import ev3dev.sensors.Button;
import ev3dev.sensors.ev3.EV3UltrasonicSensor;
import lejos.hardware.port.SensorPort;
import lejos.robotics.RangeFinderAdapter;
import lejos.robotics.navigation.DifferentialPilot;
import lejos.robotics.objectdetection.Feature;
import lejos.robotics.objectdetection.FeatureDetector;
import lejos.robotics.objectdetection.FeatureListener;
import lejos.robotics.objectdetection.RangeFeatureDetector;

import java.io.IOException;

public class FeatureAvoider2 {
     
    static final float MAX_DISTANCE = 50f;
    static final int DETECTOR_DELAY = 1000;
 
    public static void main(String[] args) throws IOException {

        final PilotConfig pilotConf = new PilotConfig();
        final DifferentialPilot pilot = pilotConf.getPilot();

        final EV3UltrasonicSensor ir = new EV3UltrasonicSensor(SensorPort.S1);
        final RangeFeatureDetector detector = new RangeFeatureDetector(
                new RangeFinderAdapter(ir.getDistanceMode()), MAX_DISTANCE, DETECTOR_DELAY);

        detector.enableDetection(true);
        pilot.forward();
         
        detector.addListener(new FeatureListener() {
            public void featureDetected(Feature feature, FeatureDetector detector) {
                detector.enableDetection(false);
                pilot.travel(-30);
                pilot.rotate(30);
                detector.enableDetection(true);
                pilot.forward();
            }       
        });

        Button.waitForAnyPress();
    }
}
```

**Comment by jabrena** [comment]
Possible `LeJOS` bug on class: `FusorDetector.java`

```
ev3dev#1|2017-06-02 20:37:16 [Thread-1] TRACE ev3dev.utils.Sysfs - cat /sys/class/lego-sensor/sensor2/value0
ev3dev#1|Exception in thread "Thread-2" java.util.ConcurrentModificationException
ev3dev#1|	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:886)
ev3dev#1|	at java.util.ArrayList$Itr.next(ArrayList.java:836)
ev3dev#1|	at lejos.robotics.objectdetection.FusorDetector$NotifyThread.run(FusorDetector.java:121)
ev3dev#1|2017-06-02 20:37:16 [Thread-1] TRACE ev3dev.utils.Sysfs - cat /sys/class/lego-sensor/sensor2/value0
```

**Comment by jabrena** [comment]
``` java
package ev3dev.examples.feature;

import ev3dev.examples.pilot.PilotConfig;
import ev3dev.sensors.Button;
import ev3dev.sensors.ev3.EV3TouchSensor;
import lejos.hardware.port.SensorPort;
import lejos.robotics.Touch;
import lejos.robotics.navigation.DifferentialPilot;
import lejos.robotics.objectdetection.*;

import java.io.IOException;

public class FeatureAvoider3 {

    public static void main(String[] args) throws IOException {

        final PilotConfig pilotConf = new PilotConfig();
        final DifferentialPilot pilot = pilotConf.getPilot();

        final int TOUCH_X_OFFSET = -4;
        final int TOUCH_Y_OFFSET = 16;
        final Touch ts = new EV3TouchSensor(SensorPort.S3);
        final FeatureDetector detector = new TouchFeatureDetector(ts, TOUCH_X_OFFSET, TOUCH_Y_OFFSET);

        detector.enableDetection(true);
        pilot.forward();
         
        detector.addListener(new FeatureListener() {
            public void featureDetected(Feature feature, FeatureDetector detector) {
                detector.enableDetection(false);
                pilot.travel(-30);
                pilot.rotate(30);
                detector.enableDetection(true);
                pilot.forward();
            }       
        });

        Button.waitForAnyPress();
    }
}
```

**Comment by jabrena** [comment]
Review completed. The package run nice with the exception of the class: `FusorDetector.java` I have to report to `LeJOS forum` a possible concurrency problem and try to do a Pull Request to solve the problem.
