### ISSUE TITLE
Review the scenario of ROS down in the middle of execution of Java process

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#395]
It is necessary to review how to protect the robot if ROS is down in the middle of the execution.

``` 
ev3dev#1|Exception in thread "main" java.lang.RuntimeException: Socket is not connected.
ev3dev#1|	at org.glassfish.tyrus.container.grizzly.GrizzlyClientSocket.send(GrizzlyClientSocket.java:311)
ev3dev#1|	at org.glassfish.tyrus.core.TyrusRemoteEndpoint.sendText(TyrusRemoteEndpoint.java:101)
ev3dev#1|	at org.glassfish.tyrus.core.RemoteEndpointWrapper.sendSyncText(RemoteEndpointWrapper.java:188)
ev3dev#1|	at org.glassfish.tyrus.core.RemoteEndpointWrapper$Basic.sendText(RemoteEndpointWrapper.java:86)
ev3dev#1|	at edu.wpi.rail.jrosbridge.Ros.send(Ros.java:416)
ev3dev#1|	at edu.wpi.rail.jrosbridge.Topic.publish(Topic.java:282)
ev3dev#1|	at ev3dev.rosbridge.publishers.EV3UltrasonicSensor.publish(EV3UltrasonicSensor.java:63)
ev3dev#1|	at examples.TeleoperationDemo.main(TeleoperationDemo.java:39)
Failed command ev3dev#1 with status 1: java -server -Djava.library.path=/usr/lib/jni/ -jar /home/robot/ros-0.1.0-SNAPSHOT-all.jar
```

**Comment by jabrena** [comment]
Rejected by LEAN
