### ISSUE TITLE
Review execution of reset command to add more delay

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#415]
**Bug Description:**
In some execution scenario, some users has experimented some problem with the Motor Registration process. In several cases, the exception appear when the program tries to execute the following action:

```
ev3dev#19|2018-03-13 18:38:28 [main] ERROR ev3dev.utils.Sysfs - File: '/sys/class/tacho-motor/motor39/command' without write permissions.
ev3dev#19|Exception in thread "main" java.lang.ExceptionInInitializerError
ev3dev#19| at examples.Pilotest.main(Pilotest.java:14)
ev3dev#19|Caused by: java.lang.RuntimeException: Operation not executed: /sys/class/tacho-motor/motor39/command with value reset
```

The users normally unplug the motors from the Brick and connect again. This problem solve temporally the situation. Reviewing with the developers, I observed that low battery levels affect the execution.

It is necessary to review how to fix the problem:

**Full execution log:**

``` java
ev3dev#19|2018-03-13 18:38:26 [main] DEBUG ev3dev.hardware.EV3DevDevice - Detecting device on port: outB
ev3dev#19|2018-03-13 18:38:26 [main] DEBUG ev3dev.hardware.EV3DevDevice - Detected port on path: /sys/class/lego-port/port5/address
ev3dev#19|2018-03-13 18:38:26 [main] DEBUG e.a.lego.motors.BaseRegulatedMotor - Setting port in mode: tacho-motor
ev3dev#19|2018-03-13 18:38:27 [main] DEBUG ev3dev.hardware.EV3DevDevice - Detecting device on port: outB
ev3dev#19|2018-03-13 18:38:27 [main] DEBUG ev3dev.hardware.EV3DevDevice - Detected port on path: /sys/class/tacho-motor/motor39/address
ev3dev#19|2018-03-13 18:38:28 [main] ERROR ev3dev.utils.Sysfs - File: '/sys/class/tacho-motor/motor39/command' without write permissions.
ev3dev#19|Exception in thread "main" java.lang.ExceptionInInitializerError
ev3dev#19| at examples.Pilotest.main(Pilotest.java:14)
ev3dev#19|Caused by: java.lang.RuntimeException: Operation not executed: /sys/class/tacho-motor/motor39/command with value reset
ev3dev#19| at ev3dev.hardware.EV3DevDevice.setStringAttribute(EV3DevDevice.java:98)
ev3dev#19| at ev3dev.actuators.lego.motors.BaseRegulatedMotor.<init>(BaseRegulatedMotor.java:82)
ev3dev#19| at ev3dev.actuators.lego.motors.NXTRegulatedMotor.<init>(NXTRegulatedMotor.java:26)
ev3dev#19| at ev3dev.actuators.lego.motors.Motor.<clinit>(Motor.java:36)
ev3dev#19| ... 1 more
Failed command ev3dev#19 with status 1: java -server -jar /home/robot/template_project_gradle-all-0.2.0.jar 
:remoteRun FAILED
```

**Comment by jabrena** [comment]
``` java
    public BaseRegulatedMotor(final Port motorPort, float moveP, float moveI, float moveD,
                              float holdP, float holdI, float holdD, int offset, int maxSpeed) {

        MAX_SPEED_AT_9V = maxSpeed;
        final String port = this.getMotorPort(motorPort);

        log.debug("Detecting motor on port: {}", port);
        this.detect(LEGO_PORT, port);
        log.debug("Setting port in mode: {}", TACHO_MOTOR);
        this.setStringAttribute(MODE, TACHO_MOTOR);
        Delay.msDelay(500);
        this.detect(TACHO_MOTOR, port);
        Delay.msDelay(500);
        this.setStringAttribute(COMMAND, RESET);
	}
```

**Comment by jabrena** [comment]
**Note:** 
This year, I will analyze logs execution to try to minimize `sysfs` calls to improve the performance.
