### ISSUE TITLE
Replace innerclasses for a generic class to solve all scenarios for EV3 Sensors

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#498]
It is necessary to design a solution to replace all inner classes used on EV3 Sensors for a simple inmutable class with a generic constructor.

This improvement, will reduce the complexity to understand the UML Class diagram

**Comment by jabrena** [comment]
https://jitpack.io/com/github/ev3dev-lang-java/ev3dev-lang-java/2.4.1-SNAPSHOT/build.log

**Comment by jabrena** [comment]
Detail about StackTrace when any user disconnect a Sensor:

```
ev3dev#35|2018-05-05 17:10:09 [main] ERROR ev3dev.utils.Sysfs - Problem reading path: /sys/class/lego-sensor/sensor3/value0
ev3dev#35|java.io.IOException: Problem reading path: /sys/class/lego-sensor/sensor3/value0
ev3dev#35|	at ev3dev.utils.Sysfs.readString(Sysfs.java:74)
ev3dev#35|	at ev3dev.utils.Sysfs.readFloat(Sysfs.java:91)
ev3dev#35|	at ev3dev.sensors.GenericMode.fetchSample(GenericMode.java:63)
ev3dev#35|	at example.robotics.ev3.sensor.USSensorExample.main(USSensorExample.java:26)
```

**Comment by jabrena** [comment]
Fixed
