### ISSUE TITLE
Create repository openjdk-ev3-test

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#513]
The testing model designed on AdoptOpenJDK split the build process in one Jenkins execution and later the testing process.

![](https://i1.wp.com/blog.adoptopenjdk.net/wp-content/uploads/2017/12/Slide1.jpg?w=720&ssl=1)

Image from the article:
https://blog.adoptopenjdk.net/2017/12/testing-java-help-count-ways

In order to follow that approach, it is necessary to develop a repository to run on AdoptOpenJDK CI

Idea for the development:
https://github.com/AdoptOpenJDK/openjdk-tests/tree/master/buildenv/docker

Related issue:
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/466
https://github.com/ev3dev/ev3dev/issues/1099
https://github.com/AdoptOpenJDK/openjdk-tests/issues/440

**Comment by jabrena** [comment]
Real EV3 with OpenJDK 10 JDK v0.5.0 compile process: OK

```
robot@ev3dev:~$ sudo update-alternatives --config java
There are 9 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                         Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-10-openjdk-armel/bin/java   1094      auto mode
  1            /opt/ejdk1.8.0/linux_arm_sflt/jre/bin/java    1         manual mode
* 2            /opt/jdk-10-build-46-v2/bin/java              1         manual mode
  3            /opt/jdk-10-build-46/bin/java                 1         manual mode
  4            /opt/jdk-9-build-46/bin/java                  1         manual mode
  5            /opt/jri-10-build-050/bin/java                10        manual mode
  6            /opt/jri-10-build-46-v2/bin/java              1         manual mode
  7            /opt/jri-10-build-46-zero/bin/java            1         manual mode
  8            /opt/jri-10-build-46/bin/java                 1         manual mode
  9            /usr/lib/jvm/java-10-openjdk-armel/bin/java   1094      manual mode

Press <enter> to keep the current choice[*], or type selection number: ^[^C
robot@ev3dev:~$ cd /opt/jdk-10-build-46-v2/bin/
robot@ev3dev:/opt/jdk-10-build-46-v2/bin$ ls
idlj       java     javap     jdb        jhsdb   jjs    jmod        jshell  jstatd   pack200  rmiregistry  servertool  wsgen
jar        javac    jcmd      jdeprscan  jimage  jlink  jps         jstack  keytool  rmic     schemagen    tnameserv   wsimport
jarsigner  javadoc  jconsole  jdeps      jinfo   jmap   jrunscript  jstat   orbd     rmid     serialver    unpack200   xjc
robot@ev3dev:/opt/jdk-10-build-46-v2/bin$ vi HelloWorld
robot@ev3dev:/opt/jdk-10-build-46-v2/bin$ vi HelloWorld.java
robot@ev3dev:/opt/jdk-10-build-46-v2/bin$ ./javac HelloWorld.java 
robot@ev3dev:/opt/jdk-10-build-46-v2/bin$ ./java HelloWorld 
Hello, World
robot@ev3dev:/opt/jdk-10-build-46-v2/bin$ 
```

**Comment by jabrena** [comment]
Real EV3 with OpenJDK 10 JDK latest Jenkins build compile process: In course
wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 0 https://ci.adoptopenjdk.net/view/ev3dev/job/openjdk-10-ev3/lastSuccessfulBuild/artifact/build/jdk-ev3.tar.gz

**Comment by jabrena** [comment]
It is necessary to to test in the cross-compiling environment the build.

**Comment by jabrena** [comment]
https://packages.debian.org/sid/libhsdis0-fcml
https://bugs.openjdk.java.net/browse/JDK-8185567
https://askubuntu.com/questions/710392/java-8-oracle-1-8-0-66-problem-with-printassembly-could-not-load-hsdis-amd64

**Comment by jabrena** [comment]
shell script wrapper:
```
#!/bin/bash
java.real -Xint "$@"
```

**Comment by jabrena** [comment]
http://www.neiland.net/blog/article/how-to-install-ant-contrib/

**Comment by jabrena** [comment]
The process run nice.
It is necessary to create a Docker image to run the whole process

**Comment by jabrena** [comment]
```
make xxx
jdk_math*
jdk_lang*
jdk_io*
jdk_beans
jdk_other
jdk_net*
jdk_nio*
jdk_security1
jdk_security2
jdk_security3
jdk_text
jdk_util*
jdk_time
jdk_management
jdk_jmx
jdk_rmi*
jdk_sound
jdk_tools
jdk_jdi
jdk_jfr
jdk_awt
```

**Comment by jabrena** [comment]
Stable development.
Pending to understand how to exclude some tests

**Comment by jabrena** [comment]
```
TEST: java/lang/annotation/loaderLeak/Main.java
TEST JDK: /opt/jdktest/jdk/bin/..

ACTION: shell -- Failed. Execution failed: exit code 1
REASON: User specified action: run shell LoaderLeak.sh 
TIME:   10.589 seconds
messages:
command: shell LoaderLeak.sh
reason: User specified action: run shell LoaderLeak.sh 
elapsed time (seconds): 10.589
STDOUT:
TESTSRC=/opt/jdktest/openjdk-tests/openjdk_regression/openjdk-jdk/test/jdk/java/lang/annotation/loaderLeak
TESTJAVA=/opt/jdktest/jdk/bin/..
COMPILEJAVA=/opt/jdktest/jdk/bin/..
TESTCLASSES=/opt/jdktest/jvmtest/openjdk_regression/work/classes/1/java/lang/annotation/loaderLeak/Main.d
CLASSPATH=
Failed 1 of 2
STDERR:
qemu: Unsupported syscall: 345
Unsupported setsockopt level=1 optname=15
javac: invalid flag: -Xint
Usage: javac <options> <source files>
use --help for a list of possible options
qemu: Unsupported syscall: 345
Unsupported setsockopt level=1 optname=15
javac: invalid flag: -Xint
Usage: javac <options> <source files>
use --help for a list of possible options
qemu: Unsupported syscall: 345
Unsupported setsockopt level=1 optname=15
Error: Could not find or load main class Main
Caused by: java.lang.ClassNotFoundException: Main
rerun:
cd /opt/jdktest/jvmtest/openjdk_regression/work/scratch/0 && \
HOME=/home/docker \
PATH=/bin:/usr/bin \
TESTSRC=/opt/jdktest/openjdk-tests/openjdk_regression/openjdk-jdk/test/jdk/java/lang/annotation/loaderLeak \
TESTSRCPATH=/opt/jdktest/openjdk-tests/openjdk_regression/openjdk-jdk/test/jdk/java/lang/annotation/loaderLeak \
TESTCLASSES=/opt/jdktest/jvmtest/openjdk_regression/work/classes/1/java/lang/annotation/loaderLeak/Main.d \
TESTCLASSPATH=/opt/jdktest/jvmtest/openjdk_regression/work/classes/1/java/lang/annotation/loaderLeak/Main.d \
COMPILEJAVA=/opt/jdktest/jdk/bin/.. \
TESTJAVA=/opt/jdktest/jdk/bin/.. \
TESTVMOPTS='-ea -esa -Xmx512m' \
TESTTOOLVMOPTS='-J-ea -J-esa -J-Xmx512m' \
TESTJAVACOPTS= \
TESTJAVAOPTS= \
TESTTIMEOUTFACTOR=4.0 \
    sh \
        /opt/jdktest/openjdk-tests/openjdk_regression/openjdk-jdk/test/jdk/java/lang/annotation/loaderLeak/LoaderLeak.sh
```

**Comment by jabrena** [comment]
```
STDOUT:
Seed from RandomFactory = -8668341758890551263L
STDERR:
Failure for Math.nextAfter(float,double):
	For inputs 1.1754941E-38	(0x0.fffffcp-126) and 0.0	(0x0.0p0)
	expected  1.1754935E-38	(0x0.fffff4p-126)
	got       1.175494E-38	(0x0.fffffap-126).
Failure for Math.nextAfter(float,double):
	For inputs -1.1754941E-38	(-0x0.fffffcp-126) and -0.0	(-0x0.0p0)
	expected  -1.1754935E-38	(-0x0.fffff4p-126)
	got       -1.175494E-38	(-0x0.fffffap-126).
Failure for StrictMath.nextAfter(float,double):
	For inputs 1.1754941E-38	(0x0.fffffcp-126) and 0.0	(0x0.0p0)
	expected  1.1754935E-38	(0x0.fffff4p-126)
	got       1.175494E-38	(0x0.fffffap-126).
Failure for StrictMath.nextAfter(float,double):
	For inputs -1.1754941E-38	(-0x0.fffffcp-126) and -0.0	(-0x0.0p0)
	expected  -1.1754935E-38	(-0x0.fffff4p-126)
	got       -1.175494E-38	(-0x0.fffffap-126).
Failure for Math.nextAfter(double,double):
	For inputs 2.2250738585072004E-308	(0x0.ffffffffffffep-1022) and 0.0	(0x0.0p0)
	expected  2.2250738585071984E-308	(0x0.ffffffffffffap-1022)
	got       2.2250738585072E-308	(0x0.ffffffffffffdp-1022).
Failure for Math.nextAfter(double,double):
	For inputs -2.2250738585072004E-308	(-0x0.ffffffffffffep-1022) and -0.0	(-0x0.0p0)
	expected  -2.2250738585071984E-308	(-0x0.ffffffffffffap-1022)
	got       -2.2250738585072E-308	(-0x0.ffffffffffffdp-1022).
Failure for StrictMath.nextAfter(double,double):
	For inputs 2.2250738585072004E-308	(0x0.ffffffffffffep-1022) and 0.0	(0x0.0p0)
	expected  2.2250738585071984E-308	(0x0.ffffffffffffap-1022)
	got       2.2250738585072E-308	(0x0.ffffffffffffdp-1022).
Failure for StrictMath.nextAfter(double,double):
	For inputs -2.2250738585072004E-308	(-0x0.ffffffffffffep-1022) and -0.0	(-0x0.0p0)
	expected  -2.2250738585071984E-308	(-0x0.ffffffffffffap-1022)
	got       -2.2250738585072E-308	(-0x0.ffffffffffffdp-1022).
Testing the recommended functions incurred 8 failures.
java.lang.RuntimeException
	at IeeeRecommendedTests.main(IeeeRecommendedTests.java:1709)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:246)
	at java.base/java.lang.Thread.run(Thread.java:844)

JavaTest Message: Test threw exception: java.lang.RuntimeException
JavaTest Message: shutting down test
```

**Comment by jabrena** [comment]
Finally, we reached the second milestone on JVM area:

- [ ] Master the process to build OpenJDK for EV3 (@JakubVanek )
- [ ] Develop a stable set of Jenkins jobs to execute regression tests and system tests with the JVM build.
