### ISSUE TITLE
Full regression tests for BrickPi+ & Raspberry Pi 3

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#588]
It is necessary to execute a full regression tests with the following combination:

Full regression execution:

**Actuators:** 

- [x] LargeMotorDemo
- [ ] LargeMotorDemo2
- [x] LargeMotorDemo3 
- [x] LargeMotorStopModesExample
- [x] MediumMotorDemo
- [x] MediumMotorStopModesExample
- [x] MotorEncoderTest
- [x] MotorEventTest
- [x] MultipleMotorsDemo
- [x] MultipleMotorsStopDemo
- [x] NXTRegulatedMotorDemo
- [x] NXTRegulatedMotorStopModesExample 
- [ ] RegulatedMotorRotateDemo
- [ ] RegulatedMotorRotateToDemo
- [ ] UnregulatedMotorDemo 
- [x] UnregulatedMotorDemo2 
- [ ] UnregulatedMotorDemo3 
- [ ] UnregulatedMotorDemo4 
- [ ] UnregulatedMutilpleMotorDemo 

**Sensors:**

- [x] BatteryDemo
- [x] ColorSensorDemo
- [x] ColorSensorDemo2
- [x] ColorSensorDemo3
- [ ] ColorSensorMultipleDemo
- [ ] GyroSensorDemo1
- [ ] GyroSensorDemo2
- [ ] GyroSensorDemo3
- [x] IRSensorDemo1
- [ ] IRSensorDemo2
- [ ] IRSensorDemo3
- [ ] IRSensorDemo4
- [x] USSensorDemo
- [ ] USSensorDemo2
- [ ] USSensorMultipleDemo
- [ ] AbsoluteIMUAccelerationTest
- [ ] AbsoluteIMUCompassTest
- [ ] AbsoluteIMUGyroTest
- [ ] AbsoluteIMUMagneticTest
- [ ] AbsoluteIMUTiltTest
- [ ] CreatePhotoDemo
- [ ] CreatePhotoEV3Demo
- [ ] FaceRecognitionDemo
- [ ] FaceRecognitionDemo2
- [ ] RecordVideoDemo
- [ ] RectanglesDemo
- [ ] TrackObjectsDemo

##Known issues in BrickPi+:

**Motors:**

- coast method is not implemented properly
- rotate is not implemented
- rotateTo is not implemented

**Sensors:**

- Gyro sensor problems
- IRSensor problems
- USSensor problems
- TouchSensor problems

**Comment by jabrena** [comment]
```
scp OpenJDK11-jdk_arm_linux_hotspot_2018-11-09-18-48.tar.gz robot@192.168.1.247:/home/robot/
robot@ev3dev:~$ sudo tar -zxvf OpenJDK11-jdk_arm_linux_hotspot_2018-11-09-18-48.tar.gz /opt 
robot@ev3dev:~$ cd /opt/
robot@ev3dev:/opt$ ls
jdk-11.0.1+13
robot@ev3dev:/opt$ sudo update-alternatives --install /usr/bin/java java /opt/jdk-11.0.1+13/bin/java 1011
update-alternatives: using /opt/jdk-11.0.1+13/bin/java to provide /usr/bin/java (java) in auto mode
robot@ev3dev:/opt$ java -version
```

**Comment by jabrena** [comment]
GyroDemo3
```
ev3dev#62|2018-11-13 20:24:00 [main] INFO  example.sensors.ev3.GyroSensorDemo3 - 59
ev3dev#62|2018-11-13 20:24:01 [main] TRACE ev3dev.utils.Sysfs - cat /sys/class/lego-sensor/sensor7/value0
ev3dev#62|2018-11-13 20:24:01 [main] TRACE ev3dev.utils.Sysfs - value: 0
ev3dev#62|2018-11-13 20:24:01 [main] TRACE ev3dev.utils.Sysfs - cat /sys/class/lego-sensor/sensor7/value1
ev3dev#62|2018-11-13 20:24:01 [main] TRACE ev3dev.utils.Sysfs - value: 0
ev3dev#62|2018-11-13 20:24:01 [main] INFO  example.sensors.ev3.GyroSensorDemo3 - Gyro angle/rate: 0
ev3dev#62|2018-11-13 20:24:01 [main] INFO  example.sensors.ev3.GyroSensorDemo3 - 60
```

```
ev3dev#4|2018-11-13 20:27:17 [main] TRACE ev3dev.utils.Sysfs - cat /sys/class/lego-sensor/sensor9/value7
ev3dev#4|2018-11-13 20:27:17 [main] TRACE ev3dev.utils.Sysfs - value: 0
ev3dev#4|Iteration: {}50
ev3dev#4|Beacon Channel 1: Heading: {}, Distance: {}00
ev3dev#4|Beacon Channel 2: Heading: {}, Distance: {}00
ev3dev#4|Beacon Channel 3: Heading: {}, Distance: {}00
ev3dev#4|Beacon Channel 4: Heading: {}, Distance: {}00
```

```
ev3dev#2|2018-11-13 20:28:18 [main] TRACE ev3dev.utils.Sysfs - value: 0
ev3dev#2|Iteration: {}39
ev3dev#2|Beacon Channel 1: Remote: {}0
ev3dev#2|Beacon Channel 2: Remote: {}0
ev3dev#2|Beacon Channel 3: Remote: {}0
ev3dev#2|Beacon Channel 4: Remote: {}0
```

```
ev3dev#11|Touch: {}1
ev3dev#11|2018-11-13 20:34:46 [main] TRACE ev3dev.utils.Sysfs - cat /sys/class/lego-sensor/sensor18/value0
ev3dev#11|2018-11-13 20:34:46 [main] TRACE ev3dev.utils.Sysfs - value: 1
ev3dev#11|Iteration: {}2
ev3dev#11|Touch: {}1
ev3dev#11|2018-11-13 20:34:47 [main] TRACE ev3dev.utils.Sysfs - cat /sys/class/lego-sensor/sensor18/value0
ev3dev#11|2018-11-13 20:34:47 [main] TRACE ev3dev.utils.Sysfs - value: 0
ev3dev#11|Iteration: {}3
ev3dev#11|Touch: {}0
ev3dev#11|2018-11-13 20:34:47 [main] TRACE ev3dev.utils.Sysfs - cat /sys/class/lego-sensor/sensor18/value0
ev3dev#11|2018-11-13 20:34:47 [main] TRACE ev3dev.utils.Sysfs - value: 1
ev3dev#11|Iteration: {}4
ev3dev#11|Touch: {}1
```

**Comment by jabrena** [comment]
I2C Sensor problem:

```
time java -jar /home/robot/template_project_gradle-2.4.17-all.jar 

ev3dev#1|2018-11-13 20:40:56 [main] INFO  ev3dev.hardware.EV3DevDistros - Providing an EV3DevDistros instance
ev3dev#1|2018-11-13 20:40:56 [main] DEBUG ev3dev.utils.Shell - Command: cat /etc/os-release
ev3dev#1|2018-11-13 20:40:56 [main] DEBUG ev3dev.hardware.EV3DevDistros - Debian Stretch detected
ev3dev#1|2018-11-13 20:40:56 [main] INFO  ev3dev.hardware.EV3DevPlatforms - Providing a EV3DevPlatforms instance
ev3dev#1|2018-11-13 20:40:56 [main] DEBUG ev3dev.hardware.EV3DevPlatforms - Detecting platform with the battery approach
ev3dev#1|2018-11-13 20:40:56 [main] DEBUG ev3dev.hardware.EV3DevFileSystem - Root Path: /sys/class
ev3dev#1|2018-11-13 20:40:56 [main] TRACE ev3dev.utils.Sysfs - ls /sys/class/power_supply/lego-ev3-battery
ev3dev#1|2018-11-13 20:40:56 [main] DEBUG ev3dev.hardware.EV3DevPlatforms - Detecting platform with the battery approach
ev3dev#1|2018-11-13 20:40:56 [main] TRACE ev3dev.utils.Sysfs - ls /sys/class/power_supply/pistorms-battery
ev3dev#1|2018-11-13 20:40:56 [main] DEBUG ev3dev.hardware.EV3DevPlatforms - Detecting platform with the battery approach
ev3dev#1|2018-11-13 20:40:56 [main] TRACE ev3dev.utils.Sysfs - ls /sys/class/power_supply/brickpi-battery
ev3dev#1|2018-11-13 20:40:56 [main] TRACE ev3dev.hardware.EV3DevPlatforms - Detected platform: BRICKPI
ev3dev#1|2018-11-13 20:40:56 [main] TRACE ev3dev.hardware.EV3DevDevice - Retrieving devices in path: 
ev3dev#1|2018-11-13 20:40:56 [main] TRACE ev3dev.utils.Sysfs - ls /sys/class/lego-port
ev3dev#1|2018-11-13 20:40:56 [main] TRACE ev3dev.hardware.EV3DevDevice - Checking devices on: /sys/class/lego-port
ev3dev#1|2018-11-13 20:40:56 [main] TRACE ev3dev.hardware.EV3DevDevice - Device 1:
ev3dev#1|2018-11-13 20:40:56 [main] TRACE ev3dev.utils.Sysfs - cat /sys/class/lego-port/port6/address
ev3dev#1|2018-11-13 20:40:56 [main] TRACE ev3dev.utils.Sysfs - value: serial0-0:MC
ev3dev#1|2018-11-13 20:40:56 [main] TRACE ev3dev.hardware.EV3DevDevice - Port expected: serial0-0:S1, actual: serial0-0:MC.
ev3dev#1|2018-11-13 20:40:56 [main] TRACE ev3dev.hardware.EV3DevDevice - Skipped device
ev3dev#1|2018-11-13 20:40:56 [main] TRACE ev3dev.hardware.EV3DevDevice - Device 2:
ev3dev#1|2018-11-13 20:40:56 [main] TRACE ev3dev.utils.Sysfs - cat /sys/class/lego-port/port4/address
ev3dev#1|2018-11-13 20:40:56 [main] TRACE ev3dev.utils.Sysfs - value: serial0-0:S3
ev3dev#1|2018-11-13 20:40:56 [main] TRACE ev3dev.hardware.EV3DevDevice - Port expected: serial0-0:S1, actual: serial0-0:S3.
ev3dev#1|2018-11-13 20:40:56 [main] TRACE ev3dev.hardware.EV3DevDevice - Skipped device
ev3dev#1|2018-11-13 20:40:56 [main] TRACE ev3dev.hardware.EV3DevDevice - Device 3:
ev3dev#1|2018-11-13 20:40:56 [main] TRACE ev3dev.utils.Sysfs - cat /sys/class/lego-port/port2/address
ev3dev#1|2018-11-13 20:40:56 [main] TRACE ev3dev.utils.Sysfs - value: serial0-0:MA
ev3dev#1|2018-11-13 20:40:56 [main] TRACE ev3dev.hardware.EV3DevDevice - Port expected: serial0-0:S1, actual: serial0-0:MA.
ev3dev#1|2018-11-13 20:40:56 [main] TRACE ev3dev.hardware.EV3DevDevice - Skipped device
ev3dev#1|2018-11-13 20:40:56 [main] TRACE ev3dev.hardware.EV3DevDevice - Device 4:
ev3dev#1|2018-11-13 20:40:56 [main] TRACE ev3dev.utils.Sysfs - cat /sys/class/lego-port/port0/address
ev3dev#1|2018-11-13 20:40:56 [main] TRACE ev3dev.utils.Sysfs - value: serial0-0:S1
ev3dev#1|2018-11-13 20:40:56 [main] TRACE ev3dev.hardware.EV3DevDevice - Port expected: serial0-0:S1, actual: serial0-0:S1.
ev3dev#1|2018-11-13 20:40:56 [main] DEBUG ev3dev.hardware.EV3DevDevice - Detected device on path: /sys/class/lego-port/port0/address, serial0-0:S1
ev3dev#1|2018-11-13 20:40:56 [main] INFO  ev3dev.hardware.EV3DevSensorDevice - detected lego port: /sys/class/lego-port/port0
ev3dev#1|2018-11-13 20:40:56 [main] TRACE ev3dev.utils.Sysfs - echo nxt-i2c > /sys/class/lego-port/port0/mode
ev3dev#1|2018-11-13 20:41:06 [main] TRACE ev3dev.utils.Sysfs - echo ms-absolute-imu 0x11 > /sys/class/lego-port/port0/set_device
ev3dev#1|2018-11-13 20:41:07 [main] TRACE ev3dev.hardware.EV3DevDevice - Retrieving devices in path: 
ev3dev#1|2018-11-13 20:41:07 [main] TRACE ev3dev.utils.Sysfs - ls /sys/class/lego-sensor
ev3dev#1|2018-11-13 20:41:07 [main] TRACE ev3dev.hardware.EV3DevDevice - Checking devices on: /sys/class/lego-sensor
ev3dev#1|2018-11-13 20:41:07 [main] TRACE ev3dev.hardware.EV3DevDevice - Device 1:
ev3dev#1|2018-11-13 20:41:07 [main] TRACE ev3dev.utils.Sysfs - cat /sys/class/lego-sensor/sensor16/address
ev3dev#1|2018-11-13 20:41:07 [main] TRACE ev3dev.utils.Sysfs - value: serial0-0:S2
ev3dev#1|2018-11-13 20:41:07 [main] TRACE ev3dev.hardware.EV3DevDevice - Port expected: serial0-0:S1, actual: serial0-0:S2.
ev3dev#1|2018-11-13 20:41:07 [main] TRACE ev3dev.hardware.EV3DevDevice - Skipped device
ev3dev#1|Exception in thread "main" java.lang.RuntimeException: The device was not detected in: serial0-0:S1
ev3dev#1|	at ev3dev.hardware.EV3DevDevice.detect(EV3DevDevice.java:85)
ev3dev#1|	at ev3dev.hardware.EV3DevSensorDevice.<init>(EV3DevSensorDevice.java:49)
ev3dev#1|	at ev3dev.sensors.BaseSensor.<init>(BaseSensor.java:22)
ev3dev#1|	at ev3dev.sensors.mindsensors.AbsoluteIMU.<init>(AbsoluteIMU.java:127)
ev3dev#1|	at example.sensors.mindsensors.AbsoluteIMUAccelerationTest.main(AbsoluteIMUAccelerationTest.java:19)
ev3dev#1|
ev3dev#1|real	0m16.658s
ev3dev#1|user	0m7.091s
ev3dev#1|sys	0m0.180s
```

**Comment by jabrena** [comment]
I need to create a summary about the issues for BrickPi+ with EV3Dev

**Comment by jabrena** [comment]
Summary:

- GyroSensor: Using the mode `gyroSensor.getAngleAndRateMode();` don't process the sensor properly. Example: GyroSensorDemo3
- IRSensor: Using the mode `ir1.getSeekMode();` don't process the sensor properly. Example: IRSensorDemo2
- IRSensor: Using the mode `ir1.getRemoteMode();` don't process the sensor properly. Example: IRSensorDemo3 
- Touch Sensor: returns Random values. Example: TouchSensorDemo
- I2C Sensor problem. Example: AbsoluteIMUAccelerationTest
