### ISSUE TITLE
Review support of BrickPi+ with EV3Dev Debian Stretch

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#590]
In the execution of the full regression of test combining BrickPi+, RaspberryPi 3 Model B+ and EV3Dev Stretch, I deteted that it is necessary to upgrade the property file: stretch.properties in order to add support for BrickPii+

This is the evidence using latest estable library:

```
time java -jar /home/robot/template_project_gradle-2.4.17-all.jar 

ev3dev#10|2018-11-13 20:19:07 [main] INFO  ev3dev.hardware.EV3DevDistros - Providing an EV3DevDistros instance
ev3dev#10|2018-11-13 20:19:07 [main] DEBUG ev3dev.utils.Shell - Command: cat /etc/os-release
ev3dev#10|2018-11-13 20:19:07 [main] DEBUG ev3dev.hardware.EV3DevDistros - Debian Stretch detected
ev3dev#10|2018-11-13 20:19:07 [main] INFO  ev3dev.hardware.EV3DevPlatforms - Providing a EV3DevPlatforms instance
ev3dev#10|2018-11-13 20:19:07 [main] DEBUG ev3dev.hardware.EV3DevPlatforms - Detecting platform with the battery approach
ev3dev#10|2018-11-13 20:19:07 [main] DEBUG ev3dev.hardware.EV3DevFileSystem - Root Path: /sys/class
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.utils.Sysfs - ls /sys/class/power_supply/lego-ev3-battery
ev3dev#10|2018-11-13 20:19:07 [main] DEBUG ev3dev.hardware.EV3DevPlatforms - Detecting platform with the battery approach
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.utils.Sysfs - ls /sys/class/power_supply/pistorms-battery
ev3dev#10|2018-11-13 20:19:07 [main] DEBUG ev3dev.hardware.EV3DevPlatforms - Detecting platform with the battery approach
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.utils.Sysfs - ls /sys/class/power_supply/brickpi-battery
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.hardware.EV3DevPlatforms - Detected platform: BRICKPI
ev3dev#10|2018-11-13 20:19:07 [main] INFO  e.a.lego.motors.BaseRegulatedMotor - Configuring motor connected on Port: A
ev3dev#10|2018-11-13 20:19:07 [main] DEBUG e.a.lego.motors.BaseRegulatedMotor - Detecting motor on port: ttyAMA0:MA
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.hardware.EV3DevDevice - Retrieving devices in path: 
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.utils.Sysfs - ls /sys/class/lego-port
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.hardware.EV3DevDevice - Checking devices on: /sys/class/lego-port
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.hardware.EV3DevDevice - Device 1:
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.utils.Sysfs - cat /sys/class/lego-port/port6/address
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.utils.Sysfs - value: serial0-0:MC
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.hardware.EV3DevDevice - Port expected: ttyAMA0:MA, actual: serial0-0:MC.
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.hardware.EV3DevDevice - Skipped device
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.hardware.EV3DevDevice - Device 2:
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.utils.Sysfs - cat /sys/class/lego-port/port4/address
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.utils.Sysfs - value: serial0-0:S3
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.hardware.EV3DevDevice - Port expected: ttyAMA0:MA, actual: serial0-0:S3.
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.hardware.EV3DevDevice - Skipped device
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.hardware.EV3DevDevice - Device 3:
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.utils.Sysfs - cat /sys/class/lego-port/port2/address
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.utils.Sysfs - value: serial0-0:MA
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.hardware.EV3DevDevice - Port expected: ttyAMA0:MA, actual: serial0-0:MA.
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.hardware.EV3DevDevice - Skipped device
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.hardware.EV3DevDevice - Device 4:
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.utils.Sysfs - cat /sys/class/lego-port/port0/address
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.utils.Sysfs - value: serial0-0:S1
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.hardware.EV3DevDevice - Port expected: ttyAMA0:MA, actual: serial0-0:S1.
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.hardware.EV3DevDevice - Skipped device
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.hardware.EV3DevDevice - Device 5:
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.utils.Sysfs - cat /sys/class/lego-port/port7/address
ev3dev#10|2018-11-13 20:19:07 [main] TRACE ev3dev.utils.Sysfs - value: serial0-0:MD
ev3dev#10|2018-11-13 20:19:08 [main] TRACE ev3dev.hardware.EV3DevDevice - Port expected: ttyAMA0:MA, actual: serial0-0:MD.
ev3dev#10|2018-11-13 20:19:08 [main] TRACE ev3dev.hardware.EV3DevDevice - Skipped device
ev3dev#10|2018-11-13 20:19:08 [main] TRACE ev3dev.hardware.EV3DevDevice - Device 6:
ev3dev#10|2018-11-13 20:19:08 [main] TRACE ev3dev.utils.Sysfs - cat /sys/class/lego-port/port5/address
ev3dev#10|2018-11-13 20:19:08 [main] TRACE ev3dev.utils.Sysfs - value: serial0-0:S4
ev3dev#10|2018-11-13 20:19:08 [main] TRACE ev3dev.hardware.EV3DevDevice - Port expected: ttyAMA0:MA, actual: serial0-0:S4.
ev3dev#10|2018-11-13 20:19:08 [main] TRACE ev3dev.hardware.EV3DevDevice - Skipped device
ev3dev#10|2018-11-13 20:19:08 [main] TRACE ev3dev.hardware.EV3DevDevice - Device 7:
ev3dev#10|2018-11-13 20:19:08 [main] TRACE ev3dev.utils.Sysfs - cat /sys/class/lego-port/port3/address
ev3dev#10|2018-11-13 20:19:08 [main] TRACE ev3dev.utils.Sysfs - value: serial0-0:MB
ev3dev#10|2018-11-13 20:19:08 [main] TRACE ev3dev.hardware.EV3DevDevice - Port expected: ttyAMA0:MA, actual: serial0-0:MB.
ev3dev#10|2018-11-13 20:19:08 [main] TRACE ev3dev.hardware.EV3DevDevice - Skipped device
ev3dev#10|2018-11-13 20:19:08 [main] TRACE ev3dev.hardware.EV3DevDevice - Device 8:
ev3dev#10|2018-11-13 20:19:08 [main] TRACE ev3dev.utils.Sysfs - cat /sys/class/lego-port/port1/address
ev3dev#10|2018-11-13 20:19:08 [main] TRACE ev3dev.utils.Sysfs - value: serial0-0:S2
ev3dev#10|2018-11-13 20:19:08 [main] TRACE ev3dev.hardware.EV3DevDevice - Port expected: ttyAMA0:MA, actual: serial0-0:S2.
ev3dev#10|2018-11-13 20:19:08 [main] TRACE ev3dev.hardware.EV3DevDevice - Skipped device
ev3dev#10|Exception in thread "main" java.lang.RuntimeException: The device was not detected in: ttyAMA0:MA
ev3dev#10|	at ev3dev.hardware.EV3DevDevice.detect(EV3DevDevice.java:85)
ev3dev#10|	at ev3dev.actuators.lego.motors.BaseRegulatedMotor.<init>(BaseRegulatedMotor.java:87)
ev3dev#10|	at ev3dev.actuators.lego.motors.EV3LargeRegulatedMotor.<init>(EV3LargeRegulatedMotor.java:26)
ev3dev#10|	at example.actuators.lego.motors.LargeMotorDemo.main(LargeMotorDemo.java:12)
ev3dev#10|
ev3dev#10|real	0m5.839s
ev3dev#10|user	0m7.505s
ev3dev#10|sys	0m0.129s
```

**Comment by jabrena** [comment]
```
robot@ev3dev:~$ dmesg
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.14.80-ev3dev-2.3.1-rpi2 (david@freyr) (gcc version 6.4.1 20171012 (Linaro GCC 6.4-2017.11)) #1 SMP Tue Nov 13 11:59:48 CST 2018
[    0.000000] CPU: ARMv7 Processor [410fd034] revision 4 (ARMv7), cr=10c5383d
[    0.000000] CPU: div instructions available: patching division code
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt: Machine model: Raspberry Pi 3 Model B Plus Rev 1.3
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] cma: Reserved 8 MiB at 0x3ac00000
[    0.000000] On node 0 totalpages: 242688
[    0.000000] free_area_init_node: node 0, pgdat 80c85a40, node_mem_map ba39f000
[    0.000000]   Normal zone: 2133 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 242688 pages, LIFO batch:31
[    0.000000] percpu: Embedded 17 pages/cpu @ba347000 s38668 r8192 d22772 u69632
[    0.000000] pcpu-alloc: s38668 r8192 d22772 u69632 alloc=17*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3 
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 240555
[    0.000000] Kernel command line: 8250.nr_uarts=1 bcm2708_fb.fbwidth=656 bcm2708_fb.fbheight=416 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  dwc_otg.lpm_enable=0 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait consoleblank=0
[    0.000000] PID hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Dentry cache hash table entries: 131072 (order: 7, 524288 bytes)
[    0.000000] Inode-cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Memory: 940224K/970752K available (7168K kernel code, 578K rwdata, 2236K rodata, 1024K init, 702K bss, 22336K reserved, 8192K cma-reserved)
[    0.000000] Virtual kernel memory layout:
                   vector  : 0xffff0000 - 0xffff1000   (   4 kB)
                   fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
                   vmalloc : 0xbb800000 - 0xff800000   (1088 MB)
                   lowmem  : 0x80000000 - 0xbb400000   ( 948 MB)
                   modules : 0x7f000000 - 0x80000000   (  16 MB)
                     .text : 0x80008000 - 0x80800000   (8160 kB)
                     .init : 0x80b00000 - 0x80c00000   (1024 kB)
                     .data : 0x80c00000 - 0x80c90a64   ( 579 kB)
                      .bss : 0x80c98258 - 0x80d47d20   ( 703 kB)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] ftrace: allocating 26436 entries in 78 pages
[    0.000000] Hierarchical RCU implementation.
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] arch_timer: cp15 timer(s) running at 19.20MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x46d987e47, max_idle_ns: 440795202767 ns
[    0.000007] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 4398046511078ns
[    0.000021] Switching to timer-based delay loop, resolution 52ns
[    0.000270] Console: colour dummy device 80x30
[    0.000785] console [tty1] enabled
[    0.000823] Calibrating delay loop (skipped), value calculated using timer frequency.. 38.40 BogoMIPS (lpj=192000)
[    0.000862] pid_max: default: 32768 minimum: 301
[    0.001176] Mount-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.001208] Mountpoint-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.002159] Disabling memory control group subsystem
[    0.002248] CPU: Testing write buffer coherency: ok
[    0.002668] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.003079] Setting up static identity map for 0x100000 - 0x10003c
[    0.003215] Hierarchical SRCU implementation.
[    0.003920] smp: Bringing up secondary CPUs ...
[    0.004661] CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
[    0.005447] CPU2: thread -1, cpu 2, socket 0, mpidr 80000002
[    0.006220] CPU3: thread -1, cpu 3, socket 0, mpidr 80000003
[    0.006323] smp: Brought up 1 node, 4 CPUs
[    0.006393] SMP: Total of 4 processors activated (153.60 BogoMIPS).
[    0.006414] CPU: All CPU(s) started in HYP mode.
[    0.006432] CPU: Virtualization extensions available.
[    0.007367] devtmpfs: initialized
[    0.017329] random: get_random_u32 called from bucket_table_alloc+0x100/0x254 with crng_init=0
[    0.017954] VFP support v0.3: implementor 41 architecture 3 part 40 variant 3 rev 4
[    0.018189] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.018232] futex hash table entries: 1024 (order: 4, 65536 bytes)
[    0.018815] pinctrl core: initialized pinctrl subsystem
[    0.019568] NET: Registered protocol family 16
[    0.022097] DMA: preallocated 1024 KiB pool for atomic coherent allocations
[    0.026704] hw-breakpoint: found 5 (+1 reserved) breakpoint and 4 watchpoint registers.
[    0.026737] hw-breakpoint: maximum watchpoint size is 8 bytes.
[    0.026933] Serial: AMBA PL011 UART driver
[    0.028545] bcm2835-mbox 3f00b880.mailbox: mailbox enabled
[    0.029001] uart-pl011 3f201000.serial: could not find pctldev for node /soc/gpio@7e200000/uart0_pins, deferring probe
[    0.060386] bcm2835-dma 3f007000.dma: DMA legacy API manager at bb813000, dmachans=0x1
[    0.061799] SCSI subsystem initialized
[    0.062035] usbcore: registered new interface driver usbfs
[    0.062108] usbcore: registered new interface driver hub
[    0.062207] usbcore: registered new device driver usb
[    0.070063] raspberrypi-firmware soc:firmware: Attached to firmware from 2018-04-09 17:46
[    0.071325] clocksource: Switched to clocksource arch_sys_counter
[    0.145871] VFS: Disk quotas dquot_6.6.0
[    0.145980] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.146179] FS-Cache: Loaded
[    0.146390] CacheFiles: Loaded
[    0.155099] NET: Registered protocol family 2
[    0.155820] TCP established hash table entries: 8192 (order: 3, 32768 bytes)
[    0.155949] TCP bind hash table entries: 8192 (order: 4, 65536 bytes)
[    0.156151] TCP: Hash tables configured (established 8192 bind 8192)
[    0.156296] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    0.156357] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    0.156596] NET: Registered protocol family 1
[    0.157057] RPC: Registered named UNIX socket transport module.
[    0.157080] RPC: Registered udp transport module.
[    0.157099] RPC: Registered tcp transport module.
[    0.157117] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.158555] hw perfevents: enabled with armv7_cortex_a7 PMU driver, 7 counters available
[    0.161248] workingset: timestamp_bits=14 max_order=18 bucket_order=4
[    0.169072] FS-Cache: Netfs 'nfs' registered for caching
[    0.169681] NFS: Registering the id_resolver key type
[    0.169723] Key type id_resolver registered
[    0.169742] Key type id_legacy registered
[    0.169770] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    0.171725] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 251)
[    0.171881] io scheduler noop registered
[    0.171902] io scheduler deadline registered (default)
[    0.172081] io scheduler cfq registered
[    0.172101] io scheduler mq-deadline registered
[    0.172121] io scheduler kyber registered
[    0.174402] BCM2708FB: allocated DMA memory fad00000
[    0.174444] BCM2708FB: allocated DMA channel 0 @ bb813000
[    0.182213] Console: switching to colour frame buffer device 82x26
[    0.188598] Serial: 8250/16550 driver, 1 ports, IRQ sharing enabled
[    0.192156] bcm2835-rng 3f104000.rng: hwrng registered
[    0.194265] vc-mem: phys_addr:0x00000000 mem_base=0x3ec00000 mem_size:0x40000000(1024 MiB)
[    0.198629] vc-sm: Videocore shared memory driver
[    0.200841] gpiomem-bcm2835 3f200000.gpiomem: Initialised: Registers at 0x3f200000
[    0.214268] brd: module loaded
[    0.224800] loop: module loaded
[    0.226811] Loading iSCSI transport class v2.0-870.
[    0.229619] libphy: Fixed MDIO Bus: probed
[    0.231681] usbcore: registered new interface driver lan78xx
[    0.233637] usbcore: registered new interface driver smsc95xx
[    0.235505] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    0.265256] dwc_otg 3f980000.usb: base=0xf0980000
[    0.467348] Core Release: 2.80a
[    0.469252] Setting default values for core params
[    0.471226] Finished setting default values for core params
[    0.673471] Using Buffer DMA mode
[    0.675462] Periodic Transfer Interrupt Enhancement - disabled
[    0.677489] Multiprocessor Interrupt Enhancement - disabled
[    0.679503] OTG VER PARAM: 0, OTG VER FLAG: 0
[    0.681498] Dedicated Tx FIFOs mode
[    0.683795] WARN::dwc_otg_hcd_init:1046: FIQ DMA bounce buffers: virt = 0xbad14000 dma = 0xfad14000 len=9024
[    0.687682] FIQ FSM acceleration enabled for :
               Non-periodic Split Transactions
               Periodic Split Transactions
               High-Speed Isochronous Endpoints
               Interrupt/Control Split Transaction hack enabled
[    0.696923] dwc_otg: Microframe scheduler enabled
[    0.696972] WARN::hcd_init_fiq:459: FIQ on core 1 at 0x80633994
[    0.698885] WARN::hcd_init_fiq:460: FIQ ASM at 0x80633cf0 length 36
[    0.700771] WARN::hcd_init_fiq:486: MPHI regs_base at 0xf0006000
[    0.702755] dwc_otg 3f980000.usb: DWC OTG Controller
[    0.704692] dwc_otg 3f980000.usb: new USB bus registered, assigned bus number 1
[    0.706676] dwc_otg 3f980000.usb: irq 62, io mem 0x00000000
[    0.708651] Init: Port Power? op_state=1
[    0.710563] Init: Power Port (0)
[    0.712627] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[    0.714583] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.716528] usb usb1: Product: DWC OTG Controller
[    0.718430] usb usb1: Manufacturer: Linux 4.14.80-ev3dev-2.3.1-rpi2 dwc_otg_hcd
[    0.720402] usb usb1: SerialNumber: 3f980000.usb
[    0.722956] hub 1-0:1.0: USB hub found
[    0.724876] hub 1-0:1.0: 1 port detected
[    0.727142] dwc_otg: FIQ enabled
[    0.727147] dwc_otg: NAK holdoff enabled
[    0.727151] dwc_otg: FIQ split-transaction FSM enabled
[    0.727161] Module dwc_common_port init
[    0.727382] usbcore: registered new interface driver usb-storage
[    0.729385] mousedev: PS/2 mouse device common for all mice
[    0.731254] i2c /dev entries driver
[    0.733232] IR NEC protocol handler initialized
[    0.735121] IR RC5(x/sz) protocol handler initialized
[    0.737009] IR RC6 protocol handler initialized
[    0.738861] IR JVC protocol handler initialized
[    0.740666] IR Sony protocol handler initialized
[    0.742492] IR SANYO protocol handler initialized
[    0.744270] IR Sharp protocol handler initialized
[    0.745978] IR MCE Keyboard/mouse protocol handler initialized
[    0.747714] IR XMP protocol handler initialized
[    0.750089] bcm2835-wdt 3f100000.watchdog: Broadcom BCM2835 watchdog timer
[    0.752197] bcm2835-cpufreq: min=600000 max=1400000
[    0.754321] sdhci: Secure Digital Host Controller Interface driver
[    0.756149] sdhci: Copyright(c) Pierre Ossman
[    0.758262] mmc-bcm2835 3f300000.mmc: could not get clk, deferring probe
[    0.760398] sdhost-bcm2835 3f202000.mmc: could not get clk, deferring probe
[    0.762366] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.765814] ledtrig-cpu: registered to indicate activity on CPUs
[    0.767923] hidraw: raw HID events driver (C) Jiri Kosina
[    0.769999] usbcore: registered new interface driver usbhid
[    0.771937] usbhid: USB HID core driver
[    0.774497] vchiq: vchiq_init_state: slot_zero = bad80000, is_master = 0
[    0.777834] [vc_sm_connected_init]: start
[    0.786531] [vc_sm_connected_init]: end - returning 0
[    0.789036] Initializing XFRM netlink socket
[    0.791047] NET: Registered protocol family 17
[    0.793168] Key type dns_resolver registered
[    0.795512] Registering SWP/SWPB emulation handler
[    0.798142] registered taskstats version 1
[    0.805823] uart-pl011 3f201000.serial: cts_event_workaround enabled
[    0.807990] 3f201000.serial: ttyAMA0 at MMIO 0x3f201000 (irq = 87, base_baud = 0) is a PL011 rev2
[    0.812340] serial serial0: tty port ttyAMA0 registered
[    0.815848] 3f215040.serial: ttyS0 at MMIO 0x0 (irq = 166, base_baud = 31250000) is a 16550
[    0.821088] mmc-bcm2835 3f300000.mmc: mmc_debug:0 mmc_debug2:0
[    0.823290] mmc-bcm2835 3f300000.mmc: DMA channel allocated
[    0.881947] sdhost: log_buf @ bad13000 (fad13000)
[    0.919212] mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
[    0.922853] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.926415] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.931127] mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
[    0.941431] Indeed it is in host mode hprt0 = 00021501
[    1.003297] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    1.006191] of_cfs_init
[    1.008109] of_cfs_init: OK
[    1.010410] Waiting for root device /dev/mmcblk0p2...
[    1.020806] random: fast init done
[    1.078860] mmc0: host does not support reading read-only switch, assuming write-enable
[    1.085942] mmc0: new high speed SDHC card at address 0260
[    1.089232] mmcblk0: mmc0:0260 NCard 3.75 GiB
[    1.092425] mmc1: new high speed SDIO card at address 0001
[    1.096007]  mmcblk0: p1 p2
[    1.122242] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    1.125888] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    1.142660] devtmpfs: mounted
[    1.147919] Freeing unused kernel memory: 1024K
[    1.161356] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    1.163533] Indeed it is in host mode hprt0 = 00001101
[    1.401667] usb 1-1: New USB device found, idVendor=0424, idProduct=2514
[    1.403952] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.406790] hub 1-1:1.0: USB hub found
[    1.409072] hub 1-1:1.0: 4 ports detected
[    1.731366] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    1.763607] systemd[1]: System time before build time, advancing clock.
[    1.861633] usb 1-1.1: New USB device found, idVendor=0424, idProduct=2514
[    1.864036] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.866964] hub 1-1.1:1.0: USB hub found
[    1.869276] hub 1-1.1:1.0: 3 ports detected
[    1.933166] NET: Registered protocol family 10
[    1.936365] Segment Routing with IPv6
[    1.967328] ip_tables: (C) 2000-2006 Netfilter Core Team
[    1.991086] random: systemd: uninitialized urandom read (16 bytes read)
[    1.998936] systemd[1]: systemd 232 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
[    2.005954] systemd[1]: Detected architecture arm.
[    2.017769] systemd[1]: Set hostname to <ev3dev>.
[    2.050149] random: systemd: uninitialized urandom read (16 bytes read)
[    2.072022] random: systemd-sysv-ge: uninitialized urandom read (16 bytes read)
[    2.224269] dwc_otg_handle_wakeup_detected_intr lxstate = 2
[    2.599792] systemd[1]: openrobertalab.service: Cannot add dependency job, ignoring: Unit openrobertalab.service is masked.
[    2.632179] systemd[1]: Listening on Journal Socket (/dev/log).
[    2.637947] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
[    2.645757] systemd[1]: Listening on udev Control Socket.
[    2.651836] systemd[1]: Created slice System Slice.
[    2.657336] systemd[1]: Started Dispatch Password Requests to Console Directory Watch.
[    2.667754] systemd[1]: Mounting Debug File System...
[    2.831431] usb 1-1.1.1: new high-speed USB device number 4 using dwc_otg
[    2.962089] usb 1-1.1.1: New USB device found, idVendor=0424, idProduct=7800
[    2.962100] usb 1-1.1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    3.233405] libphy: lan78xx-mdiobus: probed
[    3.329143] EXT4-fs (mmcblk0p2): re-mounted. Opts: errors=remount-ro
[    3.438898] systemd-journald[91]: Received request to flush runtime journal from PID 1
[    3.487990] systemd-journald[91]: File /var/log/journal/e96b1605b10744cca8aa05528c256f9c/system.journal corrupted or uncleanly shut down, renaming and replacing.
[    8.051689] lan78xx 1-1.1.1:1.0 enxb827eb29d44c: renamed from eth0
[    8.814001] uart-pl011 3f201000.serial: no DMA platform data
[    8.818865] lego-port port0: Registered 'serial0-0:S1' on 'serial0-0'.
[    8.825208] lego-port port1: Registered 'serial0-0:S2' on 'serial0-0'.
[    8.828916] lego-port port2: Registered 'serial0-0:MA' on 'serial0-0'.
[    8.834678] lego-port port2: Added new device 'serial0-0:MA:lego-nxt-motor'
[    8.837961] lego-port port3: Registered 'serial0-0:MB' on 'serial0-0'.
[    8.841215] lego-port port3: Added new device 'serial0-0:MB:lego-nxt-motor'
[    8.848943] lego-port port4: Registered 'serial0-0:S3' on 'serial0-0'.
[    8.853487] lego-port port5: Registered 'serial0-0:S4' on 'serial0-0'.
[    8.856492] lego-port port6: Registered 'serial0-0:MC' on 'serial0-0'.
[    8.859431] lego-port port6: Added new device 'serial0-0:MC:lego-nxt-motor'
[    8.865216] lego-port port7: Registered 'serial0-0:MD' on 'serial0-0'.
[    8.868153] lego-port port7: Added new device 'serial0-0:MD:lego-nxt-motor'
[    9.008781] brcmfmac: F1 signature read @0x18000000=0x15264345
[    9.014992] brcmfmac: brcmf_fw_map_chip_to_name: using brcm/brcmfmac43455-sdio.bin for chip 0x004345(17221) rev 0x000006
[    9.021593] usbcore: registered new interface driver brcmfmac
[    9.025985] tacho-motor motor0: Registered 'lego-nxt-motor' on 'serial0-0:MA'.
[    9.029547] tacho-motor motor1: Registered 'lego-nxt-motor' on 'serial0-0:MB'.
[    9.033063] tacho-motor motor2: Registered 'lego-nxt-motor' on 'serial0-0:MC'.
[    9.036311] tacho-motor motor3: Registered 'lego-nxt-motor' on 'serial0-0:MD'.
[    9.205083] random: crng init done
[    9.207507] random: 7 urandom warning(s) missed due to ratelimiting
[    9.399979] brcmfmac: brcmf_c_preinit_dcmds: Firmware version = wl0: Feb 27 2018 03:15:32 version 7.45.154 (r684107 CY) FWID 01-4fbe0b04
[    9.408687] brcmfmac: brcmf_c_preinit_dcmds: CLM version = API: 12.2 Data: 9.10.105 Compiler: 1.29.4 ClmImport: 1.36.3 Creation: 2018-03-09 18:56:28 
[   10.569299] Bluetooth: Core ver 2.22
[   10.572268] NET: Registered protocol family 31
[   10.575218] Bluetooth: HCI device and connection manager initialized
[   10.578272] Bluetooth: HCI socket layer initialized
[   10.582349] Bluetooth: L2CAP socket layer initialized
[   10.585780] Bluetooth: SCO socket layer initialized
[   10.601924] Bluetooth: HCI UART driver ver 2.3
[   10.605257] Bluetooth: HCI UART protocol H4 registered
[   10.608332] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   10.611989] Bluetooth: HCI UART protocol Broadcom registered
[   11.084235] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   11.086887] Bluetooth: BNEP filters: protocol multicast
[   11.089750] Bluetooth: BNEP socket layer initialized
[   11.504862] nf_conntrack version 0.5.0 (15360 buckets, 61440 max)
[   11.883781] IPv6: ADDRCONF(NETDEV_UP): enxb827eb29d44c: link is not ready
[   11.897360] IPv6: ADDRCONF(NETDEV_CHANGE): enxb827eb29d44c: link becomes ready
[   12.018296] 8021q: 802.1Q VLAN Support v1.8
[   12.018363] 8021q: adding VLAN 0 to HW filter on device enxb827eb29d44c
```

**Comment by jabrena** [comment]
Fixed
