### ISSUE TITLE
Avoid this case: "e.a.lego.motors.BaseRegulatedMotor - Detecting motor on port: null"

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#598]
Testing PiStorms on EV3Dev Debian Stretch, the library try to find a null port. This case need to be avoided.

```
ev3dev#3|2018-11-13 19:55:15 [main] INFO  ev3dev.hardware.EV3DevDistros - Providing an EV3DevDistros instance
ev3dev#3|2018-11-13 19:55:15 [main] DEBUG ev3dev.utils.Shell - Command: cat /etc/os-release
ev3dev#3|2018-11-13 19:55:15 [main] DEBUG ev3dev.hardware.EV3DevDistros - Debian Stretch detected
ev3dev#3|2018-11-13 19:55:15 [main] INFO  ev3dev.hardware.EV3DevPlatforms - Providing a EV3DevPlatforms instance
ev3dev#3|2018-11-13 19:55:15 [main] DEBUG ev3dev.hardware.EV3DevPlatforms - Detecting platform with the battery approach
ev3dev#3|2018-11-13 19:55:15 [main] DEBUG ev3dev.hardware.EV3DevFileSystem - Root Path: /sys/class
ev3dev#3|2018-11-13 19:55:15 [main] TRACE ev3dev.utils.Sysfs - ls /sys/class/power_supply/lego-ev3-battery
ev3dev#3|2018-11-13 19:55:15 [main] DEBUG ev3dev.hardware.EV3DevPlatforms - Detecting platform with the battery approach
ev3dev#3|2018-11-13 19:55:15 [main] TRACE ev3dev.utils.Sysfs - ls /sys/class/power_supply/pistorms-battery
ev3dev#3|2018-11-13 19:55:15 [main] DEBUG ev3dev.hardware.EV3DevPlatforms - Detecting platform with the battery approach
ev3dev#3|2018-11-13 19:55:15 [main] TRACE ev3dev.utils.Sysfs - ls /sys/class/power_supply/brickpi-battery
ev3dev#3|2018-11-13 19:55:15 [main] DEBUG ev3dev.hardware.EV3DevPlatforms - Detecting platform with the battery approach
ev3dev#3|2018-11-13 19:55:15 [main] TRACE ev3dev.utils.Sysfs - ls /sys/class/power_supply/brickpi3-battery
ev3dev#3|2018-11-13 19:55:15 [main] DEBUG ev3dev.hardware.EV3DevPlatforms - Detecting platform with the battery approach
ev3dev#3|2018-11-13 19:55:15 [main] TRACE ev3dev.utils.Sysfs - ls /sys/class/power_supply/.
ev3dev#3|2018-11-13 19:55:15 [main] TRACE ev3dev.hardware.EV3DevPlatforms - Detected platform: UNKNOWN
ev3dev#3|2018-11-13 19:55:15 [main] INFO  e.a.lego.motors.BaseRegulatedMotor - Configuring motor connected on Port: A
ev3dev#3|2018-11-13 19:55:15 [main] DEBUG e.a.lego.motors.BaseRegulatedMotor - Detecting motor on port: null
ev3dev#3|2018-11-13 19:55:15 [main] TRACE ev3dev.hardware.EV3DevDevice - Retrieving devices in path: 
ev3dev#3|2018-11-13 19:55:15 [main] TRACE ev3dev.utils.Sysfs - ls /sys/class/lego-port
ev3dev#3|Exception in thread "main" java.lang.RuntimeException: The path doesn't exist: /sys/class/lego-port
ev3dev#3|	at ev3dev.utils.Sysfs.getElements(Sysfs.java:107)
ev3dev#3|	at ev3dev.hardware.EV3DevDevice.detect(EV3DevDevice.java:57)
ev3dev#3|	at ev3dev.actuators.lego.motors.BaseRegulatedMotor.<init>(BaseRegulatedMotor.java:87)
ev3dev#3|	at ev3dev.actuators.lego.motors.EV3LargeRegulatedMotor.<init>(EV3LargeRegulatedMotor.java:26)
ev3dev#3|	at example.actuators.lego.motors.LargeMotorDemo.main(LargeMotorDemo.java:12)
ev3dev#3|
ev3dev#3|real	0m6.938s
ev3dev#3|user	0m9.093s
ev3dev#3|sys	0m0.241s
```

**Comment by jabrena** [comment]
The problem is this behaviour on this piece of code:

```
ev3dev#3|2018-11-13 19:55:15 [main] TRACE ev3dev.hardware.EV3DevPlatforms - Detected platform: UNKNOWN
ev3dev#3|2018-11-13 19:55:15 [main] INFO  e.a.lego.motors.BaseRegulatedMotor - Configuring motor connected on Port: A
ev3dev#3|2018-11-13 19:55:15 [main] DEBUG e.a.lego.motors.BaseRegulatedMotor - Detecting motor on port: null
```

If `EV3DevPlatforms` returns `UNKNOWN`, it is necessary to not continue.
The library was designed for a set of platforms.

**Comment by jabrena** [comment]
Fixed

**Comment by jabrena** [comment]
Idea to refactor a bit more
https://stackoverflow.com/questions/39329407/throw-an-exception-if-a-stream-has-no-result
