### ISSUE TITLE
InvalidPathException for log4j on Windows

### ISSUE THREAD

**Issue by gscaparrotti** [ev3dev-lang-java/ev3dev-lang-java#801]
When trying to compile the example program on Windows, the following exception happens:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileJava'.
[...]
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:///home/robot/java/libraries/slf4j-api-1.7.25.jar
	at jdk.compiler/com.sun.tools.javac.file.FSInfo.getJarClassPath(FSInfo.java:112)
	at jdk.compiler/com.sun.tools.javac.file.CacheFSInfo.getJarClassPath(CacheFSInfo.java:93)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SearchPath.addJarClassPath(Locations.java:423)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SearchPath.addFile(Locations.java:413)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SearchPath.addFiles(Locations.java:345)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SearchPath.addFiles(Locations.java:333)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SearchPath.addFiles(Locations.java:339)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SimpleLocationHandler.handleOption(Locations.java:708)
	at jdk.compiler/com.sun.tools.javac.file.Locations.handleOption(Locations.java:2062)
	at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(BaseFileManager.java:269)
	at jdk.compiler/com.sun.tools.javac.file.BaseFileManager$2.handleFileManagerOption(BaseFileManager.java:222)
	at jdk.compiler/com.sun.tools.javac.main.Option.process(Option.java:1138)
	at jdk.compiler/com.sun.tools.javac.main.Option.handleOption(Option.java:1086)
	at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(BaseFileManager.java:232)
	at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$WrappedJavaFileManager.handleOption(ClientCodeWrapper.java:265)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.doProcessArgs(Arguments.java:390)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.processArgs(Arguments.java:347)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.init(Arguments.java:246)
	at jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:185)
	... 119 more
```

The same task is executed correctly on Linux. 

I think this has to do with the manifest file which refers to some libraries using the path they will have on the brick.

**Comment by jabrena** [comment]
No feedback
